feat(react): add switch to provider to log errors
projectfluent/fluent.js pull request #619
Opened 2023-07-31 19:20 UTC by StaberindeZA

Because:

* We should allow users to control if reportErrors are reported or not.

This commit:

* Adds a class property to ReactLocalization to enable/disable logging in reportErrors.
* Allows <LocalizationProvider> to enable/disable error reporting

Closes: #411

2023-07-31 21:16 UTC, eemeli requested changes
When @stasm originally suggested using a provider prop for this, the code was structured differently, and that may have made more sense. Now, all of the error reporting calls are made from within ReactLocalization, so really the control should be via an argument of its constructor, rather than as a side effect of including it in a provider. Also, why make it a boolean rather than a function accepting an error argument?

2023-08-01 12:54 UTC, StaberindeZA commented
> When @stasm originally suggested using a provider prop for this, the code was structured differently, and that may have made more sense. Now, all of the error reporting calls are made from within ReactLocalization, so really the control should be via an argument of its constructor, rather than as a side effect of including it in a provider. Also, why make it a boolean rather than a function accepting an error argument?

Thank you for the quick reply and comments. Hmm, I did not notice the age of the issue. 😅 Your suggestions make sense. 

No specific reason for the boolean. For some reason when I initially read the issue, I missed some comments, and had in my mind that the ask was for an on/off toggle. Agreed though the function is better, and I've made the changes.

2023-08-01 13:21 UTC, eemeli approved these changes
Much better! One small change, and this should be good to merge.

2023-08-01 13:21 UTC, eemeli commented on fluent-react/src/localization.ts
> +  private reportError: (error: Error) => void;
Making this private would be a breaking change, given that it's currently public.

```suggestion
  public reportError: (error: Error) => void;
```

2023-08-01 13:53 UTC, merged